services:
  bot:
    build: .
    restart: always
    volumes:
      - ./root/files:/usr/src/bot/files:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - TOKENS=
