services:
  bot:
    build: .
    restart: on-failure:5
    volumes:
      - ./root/files:/usr/src/bot/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TOKENS=
