services:
  bot:
    build: .
    restart: always
    volumes:
      - ./root/files:/usr/files:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - NOTE_DB_PATH=/usr/files/note.sqlite
      - WORD_DB_PATH=/usr/files/word.sqlite
      - DICT_DB_PATH=/usr/files/dict.sqlite
      - CONFIG_DB_PATH=/usr/files/config.sqlite
      - BIRTHDAY_DB_PATH=/usr/files/birthday.sqlite
      - TOKENS=
